# Generated by Django 4.2 on 2026-09-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='defg',
            new_name='department',
        ),
    ]
