# Generated by Django 4.2 on 2026-09-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delete_role_department_age_alter_userinfo_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='title',
        ),
    ]
